### ISSUE TITLE
System.ArgumentException: 'Unable to establish connection to Active Directory.'

### ISSUE THREAD

**Issue by Davood-Azani** [GalacticAPI/GalacticExamples#1]
Hi dude i got this error : System.ArgumentException: 'Unable to establish connection to Active Directory.'
why?
and how to Resovle? 
I used Your example for connect to AD
![capture](https://user-images.githubusercontent.com/45258690/48898946-6ba5c880-ee63-11e8-87dc-0b28deded71c.PNG)

**Comment by Davood-Azani** [comment]
PS: I 'm using win server 2016 and active directory is active

**Comment by urChONlaN** [comment]
It tries to connect to AD over SSL port 636 instead of 389.
You can configure an SSL connection to AD or just modify the source code...
Galactic_LDAP.LDAP_SSL_PORT to Galactic_LDAP.LDAP_PORT
